name: Generate Snake

on:
  # Run automatically every 12 hours
  schedule:
    - cron: "0 */12 * * *"
  
  # Allows manual workflow run (workflow_dispatch)
  workflow_dispatch:
  
  # Run on every push to main branch
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      # Generates a snake game from a github user contributions graph
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3.3.0
        with:
          # GitHub username to read the contribution graph from
          github_user_name: abbasyasin1n2
          
          # List of files to generate
          # Supported options:
          #  - palette: A preset of color, one of [github, github-dark, github-light]
          #  - color_snake: Color of the snake
          #  - color_dots: Comma separated list of dots color (exactly 5 colors expected)
          #    First color = 0 contributions, then low to high contributions
          outputs: |
            dist/github-snake.svg?palette=github-light&color_snake=#7c3aed
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#7c3aed
            dist/github-snake-green.svg?color_snake=#00c647&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39

      # Push the generated content to the output branch
      - name: Push github-contribution-grid-snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

